language: java
jdk:
  - oraclejdk8

install: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - mvn clean
  - mvn verify -P code-quality,documentation,release

addons:
  apt:
    packages:
      - oracle-java8-installer
